package dao;

import entity.CalisanlarIsYapar;
import entity.Kullanici;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class CalisanlarIsYaparEkrani extends javax.swing.JFrame {

    DefaultTableModel model;
    Kullanici islemler = new Kullanici();

    private ArrayList<PersonelEkrani.PatronBilgi> pBilgi = new ArrayList<>();

    /**
     * Creates new form CalisanlarIsYapar
     */
    public CalisanlarIsYaparEkrani() {
        initComponents();
        //this.getContentPane().setBackground(Color.ORANGE);
        this.getContentPane().setBackground(Color.getHSBColor(44, 62, 10));
        model = (DefaultTableModel) calisan_is_yapar_tablosu.getModel();
        calisanlar_is_yaparGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        calisan_is_yapar_tablosu = new javax.swing.JTable();
        geri_alani = new javax.swing.JButton();
        arama_cubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mesaj_yazisi = new javax.swing.JLabel();
        isId_alani = new javax.swing.JTextField();
        yId_alani = new javax.swing.JTextField();
        tarih_alani = new javax.swing.JTextField();
        ekle = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pId_alani = new javax.swing.JTextField();
        guncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));

        calisan_is_yapar_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "yönetici id", "personel id ", "yapıldığı tarih", "iş id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        calisan_is_yapar_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calisan_is_yapar_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(calisan_is_yapar_tablosu);
        if (calisan_is_yapar_tablosu.getColumnModel().getColumnCount() > 0) {
            calisan_is_yapar_tablosu.getColumnModel().getColumn(0).setResizable(false);
            calisan_is_yapar_tablosu.getColumnModel().getColumn(1).setResizable(false);
            calisan_is_yapar_tablosu.getColumnModel().getColumn(2).setResizable(false);
            calisan_is_yapar_tablosu.getColumnModel().getColumn(3).setResizable(false);
        }

        geri_alani.setBackground(new java.awt.Color(204, 255, 204));
        geri_alani.setText("Geri");
        geri_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_alaniActionPerformed(evt);
            }
        });

        arama_cubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arama_cubuguActionPerformed(evt);
            }
        });
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        jLabel1.setText("Yönetici ID :");

        jLabel2.setText("Yapildiği Tarih :");

        jLabel3.setText("İş İd :");

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        ekle.setBackground(new java.awt.Color(0, 153, 204));
        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        jLabel4.setText("Personel ID :");

        guncelle.setBackground(new java.awt.Color(255, 255, 0));
        guncelle.setText("Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        sil.setBackground(new java.awt.Color(255, 0, 0));
        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(geri_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pId_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                .addGap(94, 94, 94)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yId_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tarih_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(isId_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(geri_alani))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(yId_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(isId_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(tarih_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesaj_yazisi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(pId_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(46, 46, 46)
                        .addComponent(ekle)
                        .addGap(27, 27, 27)
                        .addComponent(guncelle)
                        .addGap(32, 32, 32)
                        .addComponent(sil)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geri_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_alaniActionPerformed
        SirketEkrani sirketEkrani = new SirketEkrani(this, true);
        setVisible(false);

        sirketEkrani.setVisible(true);

    }//GEN-LAST:event_geri_alaniActionPerformed

    public void dinamikAra(String ara) {

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);

        calisan_is_yapar_tablosu.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(ara));

    }

    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();

        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void arama_cubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arama_cubuguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arama_cubuguActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        mesaj_yazisi.setText("");

        int yoneticiid = (Integer.parseInt(yId_alani.getText()));
        int personelid = (Integer.parseInt(pId_alani.getText()));
        Date yapildigitarih = Date.valueOf(tarih_alani.getText());
        int isid = (Integer.parseInt(isId_alani.getText()));

        islemler.Ekle(yoneticiid, personelid, yapildigitarih, isid);

        calisanlar_is_yaparGoruntule();

        mesaj_yazisi.setText("Yeni rapor eklendi...");

        PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
        patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
        patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
        patronBilgilendirmeEkrani.setVisible(true);

        pBilgi.add(patronBilgilendirmeEkrani);
        String message = "Hangi çalışanın hangi işlerde çalıştıını gösteren tabloya yeni bilgiler eklendi...";

        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Message is Empty");
            return;
        }
        for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
            patronBilgi.notifyChanges(message);
        }

    }//GEN-LAST:event_ekleActionPerformed

    private void calisan_is_yapar_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calisan_is_yapar_tablosuMouseClicked
        int selectedrow = calisan_is_yapar_tablosu.getSelectedRow();

        yId_alani.setText(model.getValueAt(selectedrow, 0).toString());
        pId_alani.setText(model.getValueAt(selectedrow, 1).toString());
        tarih_alani.setText(model.getValueAt(selectedrow, 2).toString());
        isId_alani.setText(model.getValueAt(selectedrow, 3).toString());

    }//GEN-LAST:event_calisan_is_yapar_tablosuMouseClicked

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        //int id = (Integer.parseInt(id_alani.getText()));
        int personelid = (Integer.parseInt(pId_alani.getText()));
        Date yapildigitarih = Date.valueOf(tarih_alani.getText());
        int isid = (Integer.parseInt(isId_alani.getText()));

        int selectedrow = calisan_is_yapar_tablosu.getSelectedRow();

        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Çalışanlar iş yapar tablosu şu anda boş..");
            } else {
                mesaj_yazisi.setText("Güncellenecek bir çslışsn işi seçin");
            }
        } else {

            int yoneticiid = (int) model.getValueAt(selectedrow, 0);

            islemler.calisanisyaparGuncelle(yoneticiid, personelid, yapildigitarih, isid);
            calisanlar_is_yaparGoruntule();
            mesaj_yazisi.setText("Çalışan ve yaptığı iş başarıyla güncellendi...");

            PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
            patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
            patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
            patronBilgilendirmeEkrani.setVisible(true);

            pBilgi.add(patronBilgilendirmeEkrani);
            String message = "Hangi çalışanın hangi işlerde çalıştıını gösteren tabloda bazı bilgiler güncellendi...";

            if (message.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Message is Empty");
                return;
            }
            for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
                patronBilgi.notifyChanges(message);
            }

        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        mesaj_yazisi.setText("");
        int selectedrow = calisan_is_yapar_tablosu.getSelectedRow();

        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Calışan iş yapar tablosu Şu Anda Boş");
            } else {
                mesaj_yazisi.setText("Lütfen silinecek bir çalışan id seçiniz..");
            }
        } else {
            int yoneticiid = (int) model.getValueAt(selectedrow, 0);
            islemler.calisanisyaparSil(yoneticiid);
            calisanlar_is_yaparGoruntule();
            mesaj_yazisi.setText("başarıyla silindi");

            PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
            patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
            patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
            patronBilgilendirmeEkrani.setVisible(true);

            pBilgi.add(patronBilgilendirmeEkrani);
            String message = "Hangi çalışanın hangi işlerde çalıştıını gösteren tabloda bazı bilgiler silindi...";

            if (message.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Message is Empty");
                return;
            }
            for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
                patronBilgi.notifyChanges(message);
            }
        }
    }//GEN-LAST:event_silActionPerformed
    public void calisanlar_is_yaparGoruntule() {

        model.setRowCount(0);

        ArrayList<CalisanlarIsYapar> calisanlar_is_yapar = new ArrayList<CalisanlarIsYapar>();

        calisanlar_is_yapar = islemler.calisanlarIsYaparGetir();
        if (calisanlar_is_yapar != null) {
            for (CalisanlarIsYapar calisanIs : calisanlar_is_yapar) {
                Object[] eklenecek = {calisanIs.getYoneticiid(), calisanIs.getPersonelid(), calisanIs.getYapildigitarih(), calisanIs.getIsid()};

                model.addRow(eklenecek);

            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalisanlarIsYaparEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalisanlarIsYaparEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalisanlarIsYaparEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalisanlarIsYaparEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalisanlarIsYaparEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JTable calisan_is_yapar_tablosu;
    private javax.swing.JButton ekle;
    private javax.swing.JButton geri_alani;
    private javax.swing.JButton guncelle;
    private javax.swing.JTextField isId_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField pId_alani;
    private javax.swing.JButton sil;
    private javax.swing.JTextField tarih_alani;
    private javax.swing.JTextField yId_alani;
    // End of variables declaration//GEN-END:variables
}
