package dao;

import entity.Depo;
import entity.Kullanici;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class DepoEkrani extends javax.swing.JFrame {

    DefaultTableModel model;
    Kullanici islemler = new Kullanici();

    private ArrayList<PersonelEkrani.PatronBilgi> pBilgi = new ArrayList<>();

    /**
     * Creates new form DepoEkrani
     */
    public DepoEkrani() {
        initComponents();
        //this.getContentPane().setBackground(Color.ORANGE);
        this.getContentPane().setBackground(Color.getHSBColor(44, 62, 10));
        model = (DefaultTableModel) urun_tablosu.getModel();
        depoGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablosu = new javax.swing.JTable();
        geri_alani = new javax.swing.JButton();
        arama_cubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mesaj_yazisi = new javax.swing.JLabel();
        id_alani = new javax.swing.JTextField();
        adet_alani = new javax.swing.JTextField();
        sirketid_alani = new javax.swing.JTextField();
        urunEkle = new javax.swing.JButton();
        urunadi_alani = new javax.swing.JTextField();
        ozellik_alani = new javax.swing.JTextField();
        guncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));

        urun_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ürün adı", "ürün özelliği", "adeti", "şirket id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        urun_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablosu);
        if (urun_tablosu.getColumnModel().getColumnCount() > 0) {
            urun_tablosu.getColumnModel().getColumn(0).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(1).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(2).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(3).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(4).setResizable(false);
        }

        geri_alani.setBackground(new java.awt.Color(204, 255, 204));
        geri_alani.setText("Geri");
        geri_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_alaniActionPerformed(evt);
            }
        });

        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        jLabel1.setText(" Id :");

        jLabel2.setText("Ürün Adı :");

        jLabel3.setText("Ürün Özelliği : ");

        jLabel4.setText("Adeti :");

        jLabel5.setText("Şirket İd :");

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        urunEkle.setBackground(new java.awt.Color(0, 153, 204));
        urunEkle.setText("ÜrÜn Ekle");
        urunEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunEkleActionPerformed(evt);
            }
        });

        guncelle.setBackground(new java.awt.Color(255, 255, 0));
        guncelle.setText("Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        sil.setBackground(new java.awt.Color(255, 0, 0));
        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_alani)
                            .addComponent(urunadi_alani)
                            .addComponent(ozellik_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sirketid_alani))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(adet_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(arama_cubugu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sil, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(urunEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(geri_alani, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geri_alani)
                .addGap(23, 23, 23)
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(adet_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(urunEkle)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(sirketid_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urunadi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mesaj_yazisi)
                    .addComponent(ozellik_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geri_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_alaniActionPerformed
        SirketEkrani sirketEkrani = new SirketEkrani(this, true);
        setVisible(false);

        sirketEkrani.setVisible(true);
    }//GEN-LAST:event_geri_alaniActionPerformed

    public void dinamikAra(String ara) {

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);

        urun_tablosu.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(ara));

    }

    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();

        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void urunEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunEkleActionPerformed
        mesaj_yazisi.setText("");

        int id = (Integer.parseInt(id_alani.getText()));
        String urunadi = urunadi_alani.getText();
        String urunozelligi = ozellik_alani.getText();
        int adeti = (Integer.parseInt(adet_alani.getText()));
        int sirketid = (Integer.parseInt(sirketid_alani.getText()));

        islemler.urunEkle(id, urunadi, urunozelligi, adeti, sirketid);

        depoGoruntule();

        mesaj_yazisi.setText("Yeni rapor eklendi...");

        PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
        patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
        patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
        patronBilgilendirmeEkrani.setVisible(true);

        pBilgi.add(patronBilgilendirmeEkrani);
        String message = "Şirket deposuna  yeni bir ürün eklendi...";
        //String message = mesaj_yazisi.getText();
        
        

        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Message is Empty");
            return;
        }
        for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
            patronBilgi.notifyChanges(message);
        }
       
      // String message = mesaj_yazisi.getText();

    }//GEN-LAST:event_urunEkleActionPerformed

    private void urun_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablosuMouseClicked
        int selectedrow = urun_tablosu.getSelectedRow();

        id_alani.setText(model.getValueAt(selectedrow, 0).toString());
        urunadi_alani.setText(model.getValueAt(selectedrow, 1).toString());
        ozellik_alani.setText(model.getValueAt(selectedrow, 2).toString());
        adet_alani.setText(model.getValueAt(selectedrow, 3).toString());
        sirketid_alani.setText(model.getValueAt(selectedrow, 4).toString());
    }//GEN-LAST:event_urun_tablosuMouseClicked

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        //int id = (Integer.parseInt(id_alani.getText()));
        String urunadi = urunadi_alani.getText();
        String urunozelligi = ozellik_alani.getText();
        int adeti = (Integer.parseInt(adet_alani.getText()));
        int sirketid = (Integer.parseInt(sirketid_alani.getText()));

        int selectedrow = urun_tablosu.getSelectedRow();

        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Ürünler Tablosu şu anda boş..");
            } else {
                mesaj_yazisi.setText("Güncellenecek bir ürün seçin");
            }
        } else {

            int id = (int) model.getValueAt(selectedrow, 0);

            islemler.depoGuncelle(id, urunadi, urunozelligi, adeti, sirketid);
            depoGoruntule();
            mesaj_yazisi.setText("Ürünler başarıla güncellendi...");

            PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
            patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
            patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
            patronBilgilendirmeEkrani.setVisible(true);

            pBilgi.add(patronBilgilendirmeEkrani);
            String message = "Şirketin  deposunda bir ürünün bilgileri güncellendi...";

            if (message.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Message is Empty");
                return;
            }
            for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
                patronBilgi.notifyChanges(message);
            }

        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        mesaj_yazisi.setText("");
        int selectedrow = urun_tablosu.getSelectedRow();

        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Ürün Tablosu Şu Anda Boş");
            } else {
                mesaj_yazisi.setText("Lütfen silinecek bir ürün seçiniz..");
            }
        } else {
            int id = (int) model.getValueAt(selectedrow, 0);
            islemler.urunSil(id);
            depoGoruntule();
            mesaj_yazisi.setText("ürün başarıyla silindi");
            
            PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
        patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
        patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
        patronBilgilendirmeEkrani.setVisible(true);

        pBilgi.add(patronBilgilendirmeEkrani);
        String message = "Şirketn deposundan bir ürün kaldırıldı...";

        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Message is Empty");
            return;
        }
        for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
            patronBilgi.notifyChanges(message);
        }

        }
    }//GEN-LAST:event_silActionPerformed

    public void depoGoruntule() {

        model.setRowCount(0);

        ArrayList<Depo> depolar = new ArrayList<Depo>();

        depolar = islemler.urunleriGetir();
        if (depolar != null) {
            for (Depo depo : depolar) {
                Object[] eklenecek = {depo.getId(), depo.getUrunadi(), depo.getUrunozelligi(), depo.getAdeti(), depo.getSirketid()};

                model.addRow(eklenecek);

            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepoEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepoEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepoEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepoEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepoEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adet_alani;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JButton geri_alani;
    private javax.swing.JButton guncelle;
    private javax.swing.JTextField id_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField ozellik_alani;
    private javax.swing.JButton sil;
    private javax.swing.JTextField sirketid_alani;
    private javax.swing.JButton urunEkle;
    private javax.swing.JTable urun_tablosu;
    private javax.swing.JTextField urunadi_alani;
    // End of variables declaration//GEN-END:variables
}
