package dao;

import entity.Isler;
import entity.Kullanici;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class IslerEkrani extends javax.swing.JFrame {

    DefaultTableModel model;
    Kullanici islemler = new Kullanici();

    private ArrayList<PersonelEkrani.PatronBilgi> pBilgi = new ArrayList<>();

    /**
     * Creates new form IslerEkrani
     */
    public IslerEkrani() {
        initComponents();
        //this.getContentPane().setBackground(Color.ORANGE);
        this.getContentPane().setBackground(Color.getHSBColor(44, 62, 10));
        model = (DefaultTableModel) isler_tablosu.getModel();
        isleriGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        isler_tablosu = new javax.swing.JTable();
        geri_alani = new javax.swing.JButton();
        arama_cubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mesaj_yazisi = new javax.swing.JLabel();
        id_alani = new javax.swing.JTextField();
        is_adi_alani = new javax.swing.JTextField();
        is_alani = new javax.swing.JTextField();
        firma_alani = new javax.swing.JTextField();
        sozlesme_alani = new javax.swing.JTextField();
        gelir_alani = new javax.swing.JTextField();
        sirket_id_alani = new javax.swing.JTextField();
        isEkle = new javax.swing.JButton();
        ısGuncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        digerGelirler_alani = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));

        isler_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "iş adı", "iş alanı", "iş yapılan firma", "sözleşme süresi", "iş geliri", "diğer gelirler", "şirket id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        isler_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isler_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(isler_tablosu);
        if (isler_tablosu.getColumnModel().getColumnCount() > 0) {
            isler_tablosu.getColumnModel().getColumn(0).setResizable(false);
            isler_tablosu.getColumnModel().getColumn(1).setResizable(false);
            isler_tablosu.getColumnModel().getColumn(2).setResizable(false);
            isler_tablosu.getColumnModel().getColumn(3).setResizable(false);
            isler_tablosu.getColumnModel().getColumn(4).setResizable(false);
            isler_tablosu.getColumnModel().getColumn(5).setResizable(false);
            isler_tablosu.getColumnModel().getColumn(6).setResizable(false);
            isler_tablosu.getColumnModel().getColumn(7).setResizable(false);
        }

        geri_alani.setBackground(new java.awt.Color(204, 255, 204));
        geri_alani.setText("Geri");
        geri_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_alaniActionPerformed(evt);
            }
        });

        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        jLabel1.setText(" Id :");

        jLabel2.setText(" İş Adı :");

        jLabel3.setText(" İş Alanı :");

        jLabel4.setText("İş Yapılan Firma :");

        jLabel5.setText("Sözleşme Süresi :");

        jLabel6.setText(" İş Geliri :");

        jLabel7.setText("Şirket Id :");

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        isEkle.setBackground(new java.awt.Color(0, 153, 255));
        isEkle.setText("İş Ekle");
        isEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isEkleActionPerformed(evt);
            }
        });

        ısGuncelle.setBackground(new java.awt.Color(255, 255, 51));
        ısGuncelle.setText("Güncelle");
        ısGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ısGuncelleActionPerformed(evt);
            }
        });

        sil.setBackground(new java.awt.Color(255, 0, 0));
        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        jLabel8.setText(" Diğer Gelirler :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(arama_cubugu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(firma_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sirket_id_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(is_adi_alani)
                                    .addComponent(is_alani))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(digerGelirler_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                            .addComponent(gelir_alani)
                                            .addComponent(sozlesme_alani))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(isEkle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ısGuncelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(geri_alani)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geri_alani)
                .addGap(15, 15, 15)
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(id_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sozlesme_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isEkle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(is_adi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gelir_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ısGuncelle))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(is_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil)
                    .addComponent(jLabel8)
                    .addComponent(digerGelirler_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(mesaj_yazisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firma_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sirket_id_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geri_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_alaniActionPerformed
        SirketEkrani sirketEkrani = new SirketEkrani(this, true);
        setVisible(false);

        sirketEkrani.setVisible(true);
    }//GEN-LAST:event_geri_alaniActionPerformed

    public void dinamikAra(String ara) {

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);

        isler_tablosu.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(ara));

    }

    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();

        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void isEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isEkleActionPerformed
        mesaj_yazisi.setText("");

        int id = (Integer.parseInt(id_alani.getText()));
        String isadi = is_adi_alani.getText();
        String isalani = is_alani.getText();
        String isyapilanfirma = firma_alani.getText();
        float sozlesmesuresi = (Float.parseFloat(sozlesme_alani.getText()));
        int isgeliri = (Integer.parseInt(gelir_alani.getText()));
        int digergelirler = (Integer.parseInt(digerGelirler_alani.getText()));
        int sirketid = (Integer.parseInt(sirket_id_alani.getText()));

        islemler.isEkle(id, isadi, isalani, isyapilanfirma, sozlesmesuresi, isgeliri, digergelirler, sirketid);

        isleriGoruntule();

        mesaj_yazisi.setText("Yeni iş eklendi...");

        PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
        patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
        patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
        patronBilgilendirmeEkrani.setVisible(true);

        pBilgi.add(patronBilgilendirmeEkrani);
        String message = "Şirket yeni bir iş aldı...";

        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Message is Empty");
            return;
        }
        for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
            patronBilgi.notifyChanges(message);
        }

    }//GEN-LAST:event_isEkleActionPerformed

    private void isler_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isler_tablosuMouseClicked
        int selectedrow = isler_tablosu.getSelectedRow();

        id_alani.setText(model.getValueAt(selectedrow, 0).toString());
        is_adi_alani.setText(model.getValueAt(selectedrow, 1).toString());
        is_alani.setText(model.getValueAt(selectedrow, 2).toString());
        firma_alani.setText(model.getValueAt(selectedrow, 3).toString());
        sozlesme_alani.setText(model.getValueAt(selectedrow, 4).toString());
        gelir_alani.setText(model.getValueAt(selectedrow, 5).toString());
        digerGelirler_alani.setText(model.getValueAt(selectedrow, 6).toString());
        sirket_id_alani.setText(model.getValueAt(selectedrow, 7).toString());
    }//GEN-LAST:event_isler_tablosuMouseClicked

    private void ısGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ısGuncelleActionPerformed
        //int id = (Integer.parseInt(id_alani.getText()));
        String isadi = is_adi_alani.getText();
        String isalani = is_alani.getText();
        String isyapilanfirma = firma_alani.getText();
        float sozlesmesuresi = (Float.parseFloat(sozlesme_alani.getText()));
        int isgeliri = (Integer.parseInt(gelir_alani.getText()));
        int digergelirler = (Integer.parseInt(digerGelirler_alani.getText()));
        int sirketid = (Integer.parseInt(sirket_id_alani.getText()));

        int selectedrow = isler_tablosu.getSelectedRow();

        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("İşler Tablosu şu anda boş..");
            } else {
                mesaj_yazisi.setText("Güncellenecek bir iş seçin");
            }
            PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
            patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
            patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
            patronBilgilendirmeEkrani.setVisible(true);

            pBilgi.add(patronBilgilendirmeEkrani);
            String message = "Şirkette yapılan  işlerden birtanesi güncellendi...";

            if (message.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Message is Empty");
                return;
            }
            for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
                patronBilgi.notifyChanges(message);
            }

        } else {

            int id = (int) model.getValueAt(selectedrow, 0);

            islemler.isGuncelle(id, isadi, isalani, isyapilanfirma, sozlesmesuresi, isgeliri, digergelirler, sirketid);
            isleriGoruntule();
            mesaj_yazisi.setText("İşler başarıla güncellendi...");

        }
    }//GEN-LAST:event_ısGuncelleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        mesaj_yazisi.setText("");
        int selectedrow = isler_tablosu.getSelectedRow();

        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("İş Tablosu Şu Anda Boş");
            } else {
                mesaj_yazisi.setText("Lütfen silinecek bir iş seçiniz..");
            }
        } else {
            int id = (int) model.getValueAt(selectedrow, 0);
            islemler.isSil(id);
            isleriGoruntule();
            mesaj_yazisi.setText("İş başarıyla silindi");
            
            PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
            patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
            patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
            patronBilgilendirmeEkrani.setVisible(true);

            pBilgi.add(patronBilgilendirmeEkrani);
            String message = "Şirket işi tamamladı ve yapılan iş kaldırıldı...";

            if (message.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Message is Empty");
                return;
            }
            for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
                patronBilgi.notifyChanges(message);
            }

        }
    }//GEN-LAST:event_silActionPerformed

    public void isleriGoruntule() {

        model.setRowCount(0);

        ArrayList<Isler> isler = new ArrayList<Isler>();

        isler = islemler.isleriGetir();
        if (isler != null) {
            for (Isler is : isler) {
                Object[] eklenecek = {is.getId(), is.getIsadi(), is.getIsalani(), is.getIsyapilanfirma(),
                    is.getSozlesmesuresi(), is.getIsgeliri(), is.getDigergelirler(), is.getSirketid()};

                model.addRow(eklenecek);

            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IslerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IslerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IslerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IslerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IslerEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JTextField digerGelirler_alani;
    private javax.swing.JTextField firma_alani;
    private javax.swing.JTextField gelir_alani;
    private javax.swing.JButton geri_alani;
    private javax.swing.JTextField id_alani;
    private javax.swing.JButton isEkle;
    private javax.swing.JTextField is_adi_alani;
    private javax.swing.JTextField is_alani;
    private javax.swing.JTable isler_tablosu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton sil;
    private javax.swing.JTextField sirket_id_alani;
    private javax.swing.JTextField sozlesme_alani;
    private javax.swing.JButton ısGuncelle;
    // End of variables declaration//GEN-END:variables
}
