
package dao;

import java.awt.Color;


public class SirketEkrani extends javax.swing.JDialog {

    /**
     * Creates new form SirketEkrani
     */
    public SirketEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       // this.getContentPane().setBackground(Color.ORANGE);
        this.getContentPane().setBackground(Color.getHSBColor(44, 62, 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        calisan_alani = new javax.swing.JButton();
        isler_alani = new javax.swing.JButton();
        depo_alani = new javax.swing.JButton();
        rapor_alani = new javax.swing.JButton();
        calisanlar_is_yapar = new javax.swing.JButton();
        gerialani = new javax.swing.JButton();
        patron_bilgi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("             OU-DK ŞİRKETİ");

        calisan_alani.setBackground(new java.awt.Color(0, 204, 204));
        calisan_alani.setText("ÇALIŞANLAR");
        calisan_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calisan_alaniActionPerformed(evt);
            }
        });

        isler_alani.setBackground(new java.awt.Color(102, 255, 102));
        isler_alani.setText("İŞLER");
        isler_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isler_alaniActionPerformed(evt);
            }
        });

        depo_alani.setBackground(new java.awt.Color(255, 255, 102));
        depo_alani.setText("DEPO");
        depo_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depo_alaniActionPerformed(evt);
            }
        });

        rapor_alani.setBackground(new java.awt.Color(204, 204, 255));
        rapor_alani.setText("RAPORLAR");
        rapor_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapor_alaniActionPerformed(evt);
            }
        });

        calisanlar_is_yapar.setBackground(new java.awt.Color(255, 51, 51));
        calisanlar_is_yapar.setText("ÇALIŞANLAR İŞ YAPAR");
        calisanlar_is_yapar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calisanlar_is_yaparActionPerformed(evt);
            }
        });

        gerialani.setBackground(new java.awt.Color(204, 255, 204));
        gerialani.setText("Geri");
        gerialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerialaniActionPerformed(evt);
            }
        });

        patron_bilgi.setBackground(new java.awt.Color(0, 204, 204));
        patron_bilgi.setText("Patron Bilgilendirme");
        patron_bilgi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patron_bilgiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerialani)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calisanlar_is_yapar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depo_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calisan_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(isler_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rapor_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(patron_bilgi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(gerialani)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calisan_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(isler_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(depo_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(rapor_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calisanlar_is_yapar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patron_bilgi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calisan_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calisan_alaniActionPerformed
        CalisanlarEkrani calisanlarEkrani = new CalisanlarEkrani();
        setVisible(false);
            
        calisanlarEkrani.setVisible(true);
    }//GEN-LAST:event_calisan_alaniActionPerformed

    private void isler_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isler_alaniActionPerformed
        IslerEkrani islerEkrani = new IslerEkrani();
        setVisible(false);
            
        islerEkrani.setVisible(true);
    }//GEN-LAST:event_isler_alaniActionPerformed

    private void depo_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depo_alaniActionPerformed
        DepoEkrani depoEkrani = new DepoEkrani();
        setVisible(false);
            
        depoEkrani.setVisible(true);
    }//GEN-LAST:event_depo_alaniActionPerformed

    private void rapor_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapor_alaniActionPerformed
        RaporlarEkrani raporlarEkrani = new RaporlarEkrani();
        setVisible(false);
            
        raporlarEkrani.setVisible(true);
    }//GEN-LAST:event_rapor_alaniActionPerformed

    private void calisanlar_is_yaparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calisanlar_is_yaparActionPerformed
        CalisanlarIsYaparEkrani calisanlarIsYaparEkrani = new CalisanlarIsYaparEkrani();
        setVisible(false);
            
        calisanlarIsYaparEkrani.setVisible(true);
    }//GEN-LAST:event_calisanlar_is_yaparActionPerformed

    private void gerialaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerialaniActionPerformed
        KullaniciEkrani kullaniciEkrani = new KullaniciEkrani();
        setVisible(false);

        kullaniciEkrani.setVisible(true);
        
    }//GEN-LAST:event_gerialaniActionPerformed

    private void patron_bilgiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patron_bilgiActionPerformed
        PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
        setVisible(false);

        patronBilgilendirmeEkrani.setVisible(true);
    }//GEN-LAST:event_patron_bilgiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SirketEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SirketEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SirketEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SirketEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SirketEkrani dialog = new SirketEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calisan_alani;
    private javax.swing.JButton calisanlar_is_yapar;
    private javax.swing.JButton depo_alani;
    private javax.swing.JButton gerialani;
    private javax.swing.JButton isler_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton patron_bilgi;
    private javax.swing.JButton rapor_alani;
    // End of variables declaration//GEN-END:variables
}
