
package dao;

import entity.Kullanici;
import entity.Yonetici;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class YoneticiEkrani extends javax.swing.JFrame {
    DefaultTableModel model;
    Kullanici islemler = new Kullanici();
    
     private ArrayList<PersonelEkrani.PatronBilgi> pBilgi = new ArrayList<>();

    /**
     * Creates new form YoneticiEkrani
     */
    public YoneticiEkrani() {
        initComponents();
        //this.getContentPane().setBackground(Color.ORANGE);
        this.getContentPane().setBackground(Color.getHSBColor(44, 62, 10));
        model = (DefaultTableModel) yonetici_tablosu.getModel();
        yoneticiGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        yonetici_tablosu = new javax.swing.JTable();
        geri_alani = new javax.swing.JButton();
        arama_cubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mesaj_yazisi = new javax.swing.JLabel();
        id_alani = new javax.swing.JTextField();
        ad_soyad_alani = new javax.swing.JTextField();
        dept_alani = new javax.swing.JTextField();
        tarih_alani = new javax.swing.JTextField();
        sozlesme_alani = new javax.swing.JTextField();
        sirket_id_alani = new javax.swing.JTextField();
        y_maas_alani = new javax.swing.JTextField();
        y_ekle = new javax.swing.JButton();
        yoneticiGuncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 100, 0, 0));

        yonetici_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad_soyad", "departman", "giriş tarihi", "sözleşme süresi", "şirket id", "yönetici maaş"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        yonetici_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yonetici_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(yonetici_tablosu);
        if (yonetici_tablosu.getColumnModel().getColumnCount() > 0) {
            yonetici_tablosu.getColumnModel().getColumn(0).setResizable(false);
            yonetici_tablosu.getColumnModel().getColumn(1).setResizable(false);
            yonetici_tablosu.getColumnModel().getColumn(2).setResizable(false);
            yonetici_tablosu.getColumnModel().getColumn(3).setResizable(false);
            yonetici_tablosu.getColumnModel().getColumn(4).setResizable(false);
            yonetici_tablosu.getColumnModel().getColumn(5).setResizable(false);
            yonetici_tablosu.getColumnModel().getColumn(6).setResizable(false);
        }

        geri_alani.setBackground(new java.awt.Color(204, 255, 204));
        geri_alani.setText("Geri");
        geri_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_alaniActionPerformed(evt);
            }
        });

        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        jLabel1.setText(" Id :");

        jLabel2.setText(" Ad Soyad :");

        jLabel3.setText(" Departman :");

        jLabel4.setText(" Giriş Tarihi :");

        jLabel5.setText(" Sözleşme Süresi :");

        jLabel6.setText(" Şirket Id :");

        jLabel7.setText(" Yönetici Maaş");

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        y_ekle.setBackground(new java.awt.Color(0, 153, 204));
        y_ekle.setText("Yönetici Ekle");
        y_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y_ekleActionPerformed(evt);
            }
        });

        yoneticiGuncelle.setBackground(new java.awt.Color(255, 255, 0));
        yoneticiGuncelle.setText("Yönetici Güncelle");
        yoneticiGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yoneticiGuncelleActionPerformed(evt);
            }
        });

        sil.setBackground(new java.awt.Color(255, 0, 0));
        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tarih_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sozlesme_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ad_soyad_alani, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dept_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                            .addComponent(id_alani))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sirket_id_alani)
                                            .addComponent(y_maas_alani)))))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(y_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yoneticiGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(geri_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geri_alani)
                .addGap(13, 13, 13)
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sozlesme_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y_ekle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ad_soyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sirket_id_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yoneticiGuncelle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dept_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y_maas_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesaj_yazisi)
                    .addComponent(tarih_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geri_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_alaniActionPerformed
        CalisanlarEkrani calisanlarEkrani = new CalisanlarEkrani();
            setVisible(false);
            
            calisanlarEkrani.setVisible(true);
    }//GEN-LAST:event_geri_alaniActionPerformed

    public void dinamikAra(String ara) {
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        
        yonetici_tablosu.setRowSorter(tr);
        
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();
        
        dinamikAra(ara);
                      
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void y_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y_ekleActionPerformed
        mesaj_yazisi.setText("");
        
        int id = (Integer.parseInt(id_alani.getText()));
        String ad_soyad = ad_soyad_alani.getText();
        String departman = dept_alani.getText();
        Date giristarihi = Date.valueOf(tarih_alani.getText());
        float sozlesmesuresi = (Float.parseFloat(sozlesme_alani.getText()));
        int sirketid = (Integer.parseInt(sirket_id_alani.getText()));
        int y_maas = (Integer.parseInt(y_maas_alani.getText()));
        
        islemler.yoneticiEkle(id,ad_soyad,departman,giristarihi,sozlesmesuresi,sirketid,y_maas);
        
        yoneticiGoruntule();
        
        mesaj_yazisi.setText("Yeni yönetici eklendi...");
        
        PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
            patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
            patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
            patronBilgilendirmeEkrani.setVisible(true);
            
            pBilgi.add(patronBilgilendirmeEkrani);
        String message = "Şirkete yeni bir yönetici eklendi...";
       
       
        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Message is Empty");
            return;
        }
        for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
            patronBilgi.notifyChanges(message);
        }
    }//GEN-LAST:event_y_ekleActionPerformed

    private void yoneticiGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yoneticiGuncelleActionPerformed
         //int id = (Integer.parseInt(id_alani.getText()));
        String ad_soyad = ad_soyad_alani.getText();
        String departman = dept_alani.getText();
        Date giristarihi = Date.valueOf(tarih_alani.getText());
        float sozlesmesuresi = (Float.parseFloat(sozlesme_alani.getText()));
        int sirketid = (Integer.parseInt(sirket_id_alani.getText()));
        int y_maas = (Integer.parseInt(y_maas_alani.getText()));
        
        int selectedrow = yonetici_tablosu.getSelectedRow();
        
        if(selectedrow == -1){
            if(model.getRowCount() ==0){
                mesaj_yazisi.setText("Personel Tablosu şu anda boş..");
            }else{
                mesaj_yazisi.setText("Güncellenecek bir yönetici seçin");
            }
        }
        else{
            
            
            
            int id= (int)model.getValueAt(selectedrow, 0);
            
            islemler.yoneticiGuncelle(id,ad_soyad,departman,giristarihi,sozlesmesuresi,sirketid,y_maas);
            yoneticiGoruntule();
            mesaj_yazisi.setText("Yönetici bilgileri başarıyla güncellendi...");
             
        }
        
        PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
        patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
        patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
        patronBilgilendirmeEkrani.setVisible(true);

        pBilgi.add(patronBilgilendirmeEkrani);
        String message = "Şirketre  bir yöneticinin bilgileri güncellendi...";

        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Message is Empty");
            return;
        }
        for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
            patronBilgi.notifyChanges(message);
        }
    }//GEN-LAST:event_yoneticiGuncelleActionPerformed

    private void yonetici_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yonetici_tablosuMouseClicked
        int selectedrow = yonetici_tablosu.getSelectedRow();
        
         
        id_alani.setText(model.getValueAt(selectedrow, 0).toString());
        ad_soyad_alani.setText(model.getValueAt(selectedrow, 1).toString());
        dept_alani.setText(model.getValueAt(selectedrow, 2).toString());
        tarih_alani.setText(model.getValueAt(selectedrow, 3).toString());
        sozlesme_alani.setText(model.getValueAt(selectedrow, 4).toString());
        sirket_id_alani.setText(model.getValueAt(selectedrow, 5).toString());
        y_maas_alani.setText(model.getValueAt(selectedrow, 6).toString());
    }//GEN-LAST:event_yonetici_tablosuMouseClicked

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        mesaj_yazisi.setText("");
        int selectedrow = yonetici_tablosu.getSelectedRow();
        
        if(selectedrow == -1) {
            if(model.getRowCount() == 0) {
                mesaj_yazisi.setText("Yönetici Tablosu Şu Anda Boş");
            }
            else{
                mesaj_yazisi.setText("Lütfen silinecek bir yönetici seçiniz..");
            }
        }
        else{
            int id = (int)model.getValueAt(selectedrow, 0);
            islemler.yoneticiSil(id);
            yoneticiGoruntule();
            mesaj_yazisi.setText(" Bir yönetici işten çıkarıldı...");
        }
        PatronBilgilendirmeEkrani patronBilgilendirmeEkrani = new PatronBilgilendirmeEkrani();
        patronBilgilendirmeEkrani.setLocation(WIDTH, WIDTH);
        patronBilgilendirmeEkrani.setTitle("Patron Bilgilendirme Ekranı");
        patronBilgilendirmeEkrani.setVisible(true);

        pBilgi.add(patronBilgilendirmeEkrani);
        String message = "Şirkette bir yönetici işten çıkarıldı...";

        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Message is Empty");
            return;
        }
        for (PersonelEkrani.PatronBilgi patronBilgi : pBilgi) {
            patronBilgi.notifyChanges(message);
        }
    }//GEN-LAST:event_silActionPerformed

    public void yoneticiGoruntule(){
        
        model.setRowCount(0);
        
        ArrayList<Yonetici> yoneticiler = new ArrayList<Yonetici>();
        
        yoneticiler = islemler.yoneticileriGetir();
        if(yoneticiler != null){
            for(Yonetici yonetici : yoneticiler){
                Object[] eklenecek = {yonetici.getId(),yonetici.getAd_soyad(),yonetici.getDepartman(),yonetici.getGiristarihi(),
                yonetici.getSozlesmesuresi(),yonetici.getSirketid(),yonetici.getY_maas()};
                
                model.addRow(eklenecek);
                
            }
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_soyad_alani;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JTextField dept_alani;
    private javax.swing.JButton geri_alani;
    private javax.swing.JTextField id_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton sil;
    private javax.swing.JTextField sirket_id_alani;
    private javax.swing.JTextField sozlesme_alani;
    private javax.swing.JTextField tarih_alani;
    private javax.swing.JButton y_ekle;
    private javax.swing.JTextField y_maas_alani;
    private javax.swing.JButton yoneticiGuncelle;
    private javax.swing.JTable yonetici_tablosu;
    // End of variables declaration//GEN-END:variables
}
